### ISSUE TITLE
[Suggestion] Control mobs spawn according to TPS or MSPT

### ISSUE THREAD

**Issue by SrBedrock** [froobynooby/FarmControl#1]
Add a system that controls the chance of spawned mobs according to tps or mspt for PaperMC users.
Being able to select the [reason](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html) for the spawn.
Example:

```yml
# Settings related to global mob spawning on the server
mob-spawning:
  # Chance to spawn mobs (percentage) at a specific TPS or MSPT?
    20: 100
    19: 75
    18: 50
    17: 35
    16: 25
    15: 15
    14: 10
    13: 5
    12: 3
    11: 1
    10: 0
    9: 0
    8: 0
    7: 0
    6: 0
    5: 0
    4: 0
    3: 0
    2: 0
    1: 0
    0: 0
  spawnreason-tps-block:
    - DROWNED
    - NATURAL
    - SPAWNER
```

**Comment by froobynooby** [comment]
Hey, that's a nice idea. I'm not too familiar with how the mob spawning system works, but I don't think plugins are able to manage it very well. The only approach I can think of to this would be cancelling the spawn events - but this just ends up making the server work harder as it continues to attempt to spawn stuff

It might be better to see if such a feature can be implemented in Paper or one of its forks

**Comment by SrBedrock** [comment]
maybe some API to control the spawn rate of spawners?

**Comment by froobynooby** [comment]
Having looked into it a bit, I don't think there's any good way to mess with spawns from a plugin perspective without upsetting the server's performance even more. Someone cleverer than I might be able to make such a plugin
