### ISSUE TITLE
cramming not working for farmcontrol affected mobs

### ISSUE THREAD

**Issue by TizoCraft** [froobynooby/FarmControl#13]
hey i have a problem with farmcontrol! if mobs get affected by farmcontrol the cramming rule wont work anymore pls fix this! if u need more info my discord is Tizo#5051 im more active on discord then on github

**Comment by froobynooby** [comment]
Cramming doesn't affect mobs that have collisions disabled. There's not much of a way around this, so you'll either need to set up a profile to manually set up a cramming rule-type profile (i.e. make a profile that allows no more than 8 mobs within a distance of 0.1 of each other, or similar) or stop using the `disable-collisions` action in those problematic situations
