### ISSUE TITLE
Adding other entities,

### ISSUE THREAD

**Issue by THEqqBULDIpp** [froobynooby/FarmControl#25]
Would it be possble to add other entities as armor_stand, minecrat or item? Currently as far as i know they dont work.
It would be grat because we would be able to prevent griefers from lagging the server without using other plugins just for that.

**Comment by jokbon** [comment]
not armor stands and items.
only need minecarts and boats

**Comment by 4L0N50asd** [comment]
i would like to have this too, also adding boats. Armor Stands and boats is one of the first things that a griefer thinks to do when lagging a server with entities

**Comment by Gray-Falcon** [comment]
Hello, this is great idea, we need it

**Comment by KellerThompson** [comment]
It would really be a great idea if they added armor stands and minecarts.

**Comment by froobynooby** [comment]
Support for vehicles, projectiles and items added in #38 - for armour stands suggest using Insights
