### ISSUE TITLE
FarmControl mistakes the latest builds of Paper as being Folia

### ISSUE THREAD

**Issue by galacticwarrior9** [froobynooby/FarmControl#29]
When the latest builds of Paper 1.20 or its forks are used with FarmControl, reactive profiles are disabled and the following message is printed in console:

> Reactive mode is not supported on Folia

I suspect this is because of https://github.com/PaperMC/Paper/commit/d6d4c78e7d88f3fcd274bceab1e6b022224096ef -- FarmControl checks for Folia by [checking for the presence of the region scheduler](https://github.com/froobynooby/FarmControl/blob/8fb2995651601c2594f564e8e0afc03b12371439/src/main/java/com/froobworld/farmcontrol/hook/scheduler/RegionisedSchedulerHook.java#L47), which is now included in Paper.

![screenshot](https://i.gyazo.com/43b4bb8fdcbf089b2e59813be78f3b24.png)

**Comment by froobynooby** [comment]
Thanks for the report
