### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by unnamed199cz** [froobynooby/FarmControl#40]
![image](https://github.com/froobynooby/FarmControl/assets/69002814/5eb08e30-f711-4ea1-a2ec-7eb33484658b)
![image](https://github.com/froobynooby/FarmControl/assets/69002814/e3b67bb4-5263-4139-a30f-e6d2f2780c65)
i dont exactly know what it means and i couldnt find any support so im sending it here
latest version
mc: 1.20.x paper

**Comment by froobynooby** [comment]
Hey, are you getting any other errors further up? For example, when your server is starting?

Could you also provide a copy of your config - https://pastebin.com/

**Comment by unnamed199cz** [comment]
hey, i finally fixed it by looking into console, the whole plugin got disabled once i had one more space before anything in profiles

**Comment by froobynooby** [comment]
Awesome, glad you could get it working again
