### ISSUE TITLE
No error but the plugin doesnt affect any entities, but should

### ISSUE THREAD

**Issue by pjindras** [froobynooby/FarmControl#43]
Purpur 1.20.4 + Velocity

Profiles: https://paste.gg/p/anonymous/e5399b7d4e1744f3bcb40b582eea9797
Config: https://paste.gg/p/anonymous/6d2511ec34644d009c7facceb9a53184

There are a huge farms, but the plugin doesnt do any action, but should, what I configured wrong? There is no error message.

**Comment by froobynooby** [comment]
Hey, I tried with your configs and was getting the expected result - your configs are only set to remove random movements and disable collisions within animal farms greater than 15 mobs in size, such as this:
![2024-03-12_19 25 19](https://github.com/froobynooby/FarmControl/assets/4980841/9b77c506-da00-4299-aa94-968b2c296de4)

**Comment by pjindras** [comment]
![image](https://github.com/froobynooby/FarmControl/assets/45400186/36744ae5-be91-4659-8e31-2b806ab3e2b6)
Yes, but it doesnt do any action, and in this count it should also disable AI and trim the farm with amount like this.

**Comment by froobynooby** [comment]
I just tried with the latest Purpur 1.20.4 and the configs you provided, and it's still working for me. My only thought is that it could be another plugin causing the entities to be excluded - I would suggest disabling exclusions in the FarmControl config.yml and reloading the plugin with `/farmcontrol reload` to see if it makes any difference
