### ISSUE TITLE
[bug] potential memory leak

### ISSUE THREAD

**Issue by hkkongou** [froobynooby/FarmControl#6]
hi, i am alaysising my server's memory leak problem, i use eclipse memory analyser and found out that , farm control is one of the leak problem suspect.

please check the picture below..

![image](https://user-images.githubusercontent.com/61608872/129122323-fb0d568f-637e-42aa-9912-4055600353ee.png)

**Comment by froobynooby** [comment]
Hey, thanks for the report. I've made a potential fix - would you mind testing [FarmControl-1.1.8.zip](https://github.com/froobynooby/FarmControl/files/6985731/FarmControl-1.1.8.zip) to see if it helps? You will need to extract the plugin jar file from the zip archive

**Comment by hkkongou** [comment]
sure
let me try try for a few days

**Comment by hkkongou** [comment]
seems better now
memory analyser does not show farm control in leak suspects now
