### ISSUE TITLE
[Suggestion] Disable dropping of items for purged entities.

### ISSUE THREAD

**Issue by ultraic-space** [froobynooby/FarmControl#8]
Zombies in caves would bunch up, be killed by a purging profile, new zombie spawns would pick up the rotten flesh they had, and they would be marked as persistent. I might be doing some wrong things here, and I've changed the despawn rates for mob drops to be faster too.

**Comment by froobynooby** [comment]
Hey, I would recommend using `remove` over `kill` in that situation, as `remove` won't drop any items
